const fs = require('fs');
const path = require('path');

const data = {
  vi: {
    "Rau xanh giàu chất xơ giúp làm chậm quá trình hấp thu đường vào máu, giữ đường huyết ổn định sau bữa ăn. Nên ăn ít nhất 3-4 khẩu phần rau mỗi ngày. Các loại rau tốt nhất: rau cải xanh, bông cải xanh, rau muống, đậu bắp, cà chua, dưa leo.": "Rau xanh giàu chất xơ giúp làm chậm quá trình hấp thu đường vào máu, giữ đường huyết ổn định sau bữa ăn. Nên ăn ít nhất 3-4 khẩu phần rau mỗi ngày. Các loại rau tốt nhất: rau cải xanh, bông cải xanh, rau muống, đậu bắp, cà chua, dưa leo.",
    "Ngũ cốc nguyên hạt có chỉ số đường huyết (GI) thấp hơn gạo trắng, giúp giải phóng năng lượng từ từ và duy trì đường huyết ổn định. Thay thế 50-70% cơm trắng bằng gạo lứt, hoặc ăn yến mạch vào buổi sáng.": "Ngũ cốc nguyên hạt có chỉ số đường huyết (GI) thấp hơn gạo trắng, giúp giải phóng năng lượng từ từ và duy trì đường huyết ổn định. Thay thế 50-70% cơm trắng bằng gạo lứt, hoặc ăn yến mạch vào buổi sáng.",
    "Protein giúp bạn no lâu hơn mà không làm tăng đường huyết đột ngột. Các nguồn protein tốt cho bệnh nhân tiểu đường: cá hồi, cá thu, ức gà, đậu hũ, trứng, sữa chua không đường. Nên ăn 2-3 khẩu phần protein mỗi ngày.": "Protein giúp bạn no lâu hơn mà không làm tăng đường huyết đột ngột. Các nguồn protein tốt cho bệnh nhân tiểu đường: cá hồi, cá thu, ức gà, đậu hũ, trứng, sữa chua không đường. Nên ăn 2-3 khẩu phần protein mỗi ngày.",
    "Đường và đồ ngọt làm tăng đường huyết rất nhanh. Tuyệt đối tránh: nước ngọt có ga, nước trái cây đóng hộp, bánh ngọt, kẹo, đường trắng, mật ong (ở lượng lớn). Nếu thèm ngọt, có thể dùng trái cây tươi với lượng vừa phải.": "Đường và đồ ngọt làm tăng đường huyết rất nhanh. Tuyệt đối tránh: nước ngọt có ga, nước trái cây đóng hộp, bánh ngọt, kẹo, đường trắng, mật ong (ở lượng lớn). Nếu thèm ngọt, có thể dùng trái cây tươi với lượng vừa phải.",
    "Tinh bột trắng có chỉ số đường huyết cao, nhanh chóng chuyển hóa thành đường trong máu. Nên hạn chế: cơm trắng (không quá 1 chén/bữa), bánh mì trắng, bún, phở, bánh gạo. Thay thế bằng ngũ cốc nguyên hạt và rau củ.": "Tinh bột trắng có chỉ số đường huyết cao, nhanh chóng chuyển hóa thành đường trong máu. Nên hạn chế: cơm trắng (không quá 1 chén/bữa), bánh mì trắng, bún, phở, bánh gạo. Thay thế bằng ngũ cốc nguyên hạt và rau củ.",
    "Rượu bia có thể gây hạ đường huyết nguy hiểm, đặc biệt khi bụng đói hoặc khi đang dùng thuốc tiểu đường. Nếu uống: không uống khi đói, uống cùng bữa ăn, giới hạn 1-2 đơn vị/ngày. Không uống nếu đường huyết đang thấp.": "Rượu bia có thể gây hạ đường huyết nguy hiểm, đặc biệt khi bụng đói hoặc khi đang dùng thuốc tiểu đường. Nếu uống: không uống khi đói, uống cùng bữa ăn, giới hạn 1-2 đơn vị/ngày. Không uống nếu đường huyết đang thấp.",
    "Đi bộ nhẹ nhàng 15-30 phút sau bữa ăn giúp cơ thể sử dụng glucose hiệu quả hơn, từ đó hạ đường huyết sau ăn. Bắt đầu đi bộ khoảng 30-60 phút sau khi ăn xong. Tốc độ vừa phải, không cần nhanh.": "Đi bộ nhẹ nhàng 15-30 phút sau bữa ăn giúp cơ thể sử dụng glucose hiệu quả hơn, từ đó hạ đường huyết sau ăn. Bắt đầu đi bộ khoảng 30-60 phút sau khi ăn xong. Tốc độ vừa phải, không cần nhanh.",
    "Vận động thường xuyên giúp cơ thể nhạy cảm hơn với insulin, kiểm soát đường huyết tốt hơn và duy trì cân nặng khỏe mạnh. Khuyến nghị: ít nhất 150 phút vận động vừa/tuần. Các bài tập phù hợp: đi bộ, đạp xe, bơi lội, yoga, dưỡng sinh.": "Vận động thường xuyên giúp cơ thể nhạy cảm hơn với insulin, kiểm soát đường huyết tốt hơn và duy trì cân nặng khỏe mạnh. Khuyến nghị: ít nhất 150 phút vận động vừa/tuần. Các bài tập phù hợp: đi bộ, đạp xe, bơi lội, yoga, dưỡng sinh.",
    "Triệu chứng hạ đường huyết: run tay, vã mồ hôi, tim đập nhanh, chóng mặt, yếu sức, đói cồn cào, mờ mắt, khó tập trung. Xử lý ngay: Ăn ngay 15g đường nhanh (3 viên đường hoặc 150ml nước trái cây hoặc 1 muỗng canh mật ong). Nghỉ ngơi 15 phút rồi đo lại đường huyết. Nếu vẫn thấp hoặc không tỉnh táo, gọi cấp cứu 115 ngay lập tức.": "Triệu chứng hạ đường huyết: run tay, vã mồ hôi, tim đập nhanh, chóng mặt, yếu sức, đói cồn cào, mờ mắt, khó tập trung. Xử lý ngay: Ăn ngay 15g đường nhanh (3 viên đường hoặc 150ml nước trái cây hoặc 1 muỗng canh mật ong). Nghỉ ngơi 15 phút rồi đo lại đường huyết. Nếu vẫn thấp hoặc không tỉnh táo, gọi cấp cứu 115 ngay lập tức.",
    "Triệu chứng tăng đường huyết nguy hiểm: khát nước dữ dội, tiểu nhiều, mờ mắt, đau đầu, mệt mỏi, buồn nôn. Nếu đường huyết > 13.9 mmol/L kèm triệu chứng trên, cần liên hệ bác sĩ ngay. Nếu > 16.7 mmol/L hoặc có nôn mửa, khó thở — gọi cấp cứu 115.": "Triệu chứng tăng đường huyết nguy hiểm: khát nước dữ dội, tiểu nhiều, mờ mắt, đau đầu, mệt mỏi, buồn nôn. Nếu đường huyết > 13.9 mmol/L kèm triệu chứng trên, cần liên hệ bác sĩ ngay. Nếu > 16.7 mmol/L hoặc có nôn mửa, khó thở — gọi cấp cứu 115."
  },
  en: {
    "Rau xanh giàu chất xơ giúp làm chậm quá trình hấp thu đường vào máu, giữ đường huyết ổn định sau bữa ăn. Nên ăn ít nhất 3-4 khẩu phần rau mỗi ngày. Các loại rau tốt nhất: rau cải xanh, bông cải xanh, rau muống, đậu bắp, cà chua, dưa leo.": "Fiber-rich greens slow down sugar absorption into the blood, keeping blood sugar stable after meals. Eat at least 3-4 servings of vegetables daily. Best choices: mustard greens, broccoli, water spinach, okra, tomatoes, cucumbers.",
    "Ngũ cốc nguyên hạt có chỉ số đường huyết (GI) thấp hơn gạo trắng, giúp giải phóng năng lượng từ từ và duy trì đường huyết ổn định. Thay thế 50-70% cơm trắng bằng gạo lứt, hoặc ăn yến mạch vào buổi sáng.": "Whole grains have a lower glycemic index (GI) than white rice, releasing energy slowly and maintaining stable blood sugar. Replace 50-70% of white rice with brown rice, or eat oats for breakfast.",
    "Protein giúp bạn no lâu hơn mà không làm tăng đường huyết đột ngột. Các nguồn protein tốt cho bệnh nhân tiểu đường: cá hồi, cá thu, ức gà, đậu hũ, trứng, sữa chua không đường. Nên ăn 2-3 khẩu phần protein mỗi ngày.": "Protein keeps you full longer without causing a sudden blood sugar spike. Good protein sources for diabetics: salmon, mackerel, chicken breast, tofu, eggs, unsweetened yogurt. Eat 2-3 servings of protein daily.",
    "Đường và đồ ngọt làm tăng đường huyết rất nhanh. Tuyệt đối tránh: nước ngọt có ga, nước trái cây đóng hộp, bánh ngọt, kẹo, đường trắng, mật ong (ở lượng lớn). Nếu thèm ngọt, có thể dùng trái cây tươi với lượng vừa phải.": "Sugar and sweets increase blood sugar very quickly. Absolutely avoid: carbonated drinks, canned juices, pastries, candies, white sugar, honey (in large amounts). If you crave sweets, you can have a moderate amount of fresh fruit.",
    "Tinh bột trắng có chỉ số đường huyết cao, nhanh chóng chuyển hóa thành đường trong máu. Nên hạn chế: cơm trắng (không quá 1 chén/bữa), bánh mì trắng, bún, phở, bánh gạo. Thay thế bằng ngũ cốc nguyên hạt và rau củ.": "White starch has a high glycemic index and quickly converts to sugar in the blood. Limit: white rice (no more than 1 bowl/meal), white bread, noodles, rice cakes. Replace with whole grains and vegetables.",
    "Rượu bia có thể gây hạ đường huyết nguy hiểm, đặc biệt khi bụng đói hoặc khi đang dùng thuốc tiểu đường. Nếu uống: không uống khi đói, uống cùng bữa ăn, giới hạn 1-2 đơn vị/ngày. Không uống nếu đường huyết đang thấp.": "Alcohol can cause dangerous hypoglycemia, especially on an empty stomach or when taking diabetes medication. If you drink: don't drink on an empty stomach, drink with meals, limit to 1-2 units/day. Don't drink if blood sugar is currently low.",
    "Đi bộ nhẹ nhàng 15-30 phút sau bữa ăn giúp cơ thể sử dụng glucose hiệu quả hơn, từ đó hạ đường huyết sau ăn. Bắt đầu đi bộ khoảng 30-60 phút sau khi ăn xong. Tốc độ vừa phải, không cần nhanh.": "A gentle 15-30 minute walk after meals helps the body use glucose more efficiently, thereby lowering post-meal blood sugar. Start walking about 30-60 minutes after finishing your meal. Moderate pace, no need to be fast.",
    "Vận động thường xuyên giúp cơ thể nhạy cảm hơn với insulin, kiểm soát đường huyết tốt hơn và duy trì cân nặng khỏe mạnh. Khuyến nghị: ít nhất 150 phút vận động vừa/tuần. Các bài tập phù hợp: đi bộ, đạp xe, bơi lội, yoga, dưỡng sinh.": "Regular exercise makes the body more sensitive to insulin, better controls blood sugar, and maintains a healthy weight. Recommendation: at least 150 minutes of moderate exercise/week. Suitable exercises: walking, cycling, swimming, yoga.",
    "Triệu chứng hạ đường huyết: run tay, vã mồ hôi, tim đập nhanh, chóng mặt, yếu sức, đói cồn cào, mờ mắt, khó tập trung. Xử lý ngay: Ăn ngay 15g đường nhanh (3 viên đường hoặc 150ml nước trái cây hoặc 1 muỗng canh mật ong). Nghỉ ngơi 15 phút rồi đo lại đường huyết. Nếu vẫn thấp hoặc không tỉnh táo, gọi cấp cứu 115 ngay lập tức.": "Symptoms of hypoglycemia: trembling, sweating, rapid heartbeat, dizziness, weakness, intense hunger, blurred vision, difficulty concentrating. Treat immediately: Eat 15g of fast-acting sugar (3 sugar cubes or 150ml of juice or 1 tbsp of honey). Rest 15 mins then recheck. If still low or unconscious, call 115 immediately.",
    "Triệu chứng tăng đường huyết nguy hiểm: khát nước dữ dội, tiểu nhiều, mờ mắt, đau đầu, mệt mỏi, buồn nôn. Nếu đường huyết > 13.9 mmol/L kèm triệu chứng trên, cần liên hệ bác sĩ ngay. Nếu > 16.7 mmol/L hoặc có nôn mửa, khó thở — gọi cấp cứu 115.": "Symptoms of dangerous hyperglycemia: intense thirst, frequent urination, blurred vision, headache, fatigue, nausea. If blood sugar > 13.9 mmol/L with these symptoms, contact a doctor immediately. If > 16.7 mmol/L or there is vomiting, shortness of breath — call 115."
  },
  lo: {
    "Rau xanh giàu chất xơ giúp làm chậm quá trình hấp thu đường vào máu, giữ đường huyết ổn định sau bữa ăn. Nên ăn ít nhất 3-4 khẩu phần rau mỗi ngày. Các loại rau tốt nhất: rau cải xanh, bông cải xanh, rau muống, đậu bắp, cà chua, dưa leo.": "ຜັກສີຂຽວທີ່ອຸດົມດ້ວຍເສັ້ນໄຍຊ່ວຍຊະລໍການດູດຊຶມນ້ຳຕານເຂົ້າສູ່ເລືອດ, ຮັກສາລະດັບນ້ຳຕານໃຫ້ຄົງທີ່ຫຼັງອາຫານ. ກິນຜັກຢ່າງໜ້ອຍ 3-4 ຄາບຕໍ່ມື້. ທາງເລືອກທີ່ດີທີ່ສຸດ: ຜັກກາດຂຽວ, ບຣອກໂຄລີ, ຜັກບົ້ງ, ໝາກຖົ່ວ, ໝາກເລັ່ນ, ໝາກແຕງ.",
    "Ngũ cốc nguyên hạt có chỉ số đường huyết (GI) thấp hơn gạo trắng, giúp giải phóng năng lượng từ từ và duy trì đường huyết ổn định. Thay thế 50-70% cơm trắng bằng gạo lứt, hoặc ăn yến mạch vào buổi sáng.": "ທັນຍາພືດເຕັມເມັດມີດັດຊະນີນ້ຳຕານ (GI) ຕ່ຳກວ່າເຂົ້າຂາວ, ປ່ອຍພະລັງງານຊ້າໆ ແລະ ຮັກສາລະດັບນ້ຳຕານໃຫ້ຄົງທີ່. ປ່ຽນ 50-70% ຂອງເຂົ້າຂາວດ້ວຍເຂົ້າກ້ອງ, ຫຼື ກິນເຂົ້າໂອດເປັນອາຫານເຊົ້າ.",
    "Protein giúp bạn no lâu hơn mà không làm tăng đường huyết đột ngột. Các nguồn protein tốt cho bệnh nhân tiểu đường: cá hồi, cá thu, ức gà, đậu hũ, trứng, sữa chua không đường. Nên ăn 2-3 khẩu phần protein mỗi ngày.": "ໂປຣຕີນຊ່ວຍໃຫ້ທ່ານອີ່ມດົນຂຶ້ນໂດຍບໍ່ເຮັດໃຫ້ນ້ຳຕານໃນເລືອດເພີ່ມຂຶ້ນຢ່າງກະທັນຫັນ. ແຫຼ່ງໂປຣຕີນທີ່ດີສຳລັບຄົນເປັນເບົາຫວານ: ປາແຊລມອນ, ປາທູ, ເອິກໄກ່, ເຕົ້າຫູ້, ໄຂ່, ໂຢເກິດບໍ່ຫວານ. ກິນໂປຣຕີນ 2-3 ຄາບຕໍ່ມື້.",
    "Đường và đồ ngọt làm tăng đường huyết rất nhanh. Tuyệt đối tránh: nước ngọt có ga, nước trái cây đóng hộp, bánh ngọt, kẹo, đường trắng, mật ong (ở lượng lớn). Nếu thèm ngọt, có thể dùng trái cây tươi với lượng vừa phải.": "ນ້ຳຕານແລະເຂົ້າໜົມຫວານເຮັດໃຫ້ນ້ຳຕານໃນເລືອດເພີ່ມຂຶ້ນຢ່າງໄວວາ. ຫຼີກເວັ້ນຢ່າງເດັດຂາດ: ເຄື່ອງດື່ມທີ່ມີກາກບອນ, ນ້ຳໝາກໄມ້ກະປ໋ອງ, ເຂົ້າໜົມເຄັກ, ເຂົ້າໜົມອົມ, ນ້ຳຕານຂາວ, ນ້ຳເຜິ້ງ (ໃນປະລິມານຫຼາຍ). ຖ້າທ່ານຢາກຂອງຫວານ, ທ່ານສາມາດກິນໝາກໄມ້ສົດໃນປະລິມານປານກາງ.",
    "Tinh bột trắng có chỉ số đường huyết cao, nhanh chóng chuyển hóa thành đường trong máu. Nên hạn chế: cơm trắng (không quá 1 chén/bữa), bánh mì trắng, bún, phở, bánh gạo. Thay thế bằng ngũ cốc nguyên hạt và rau củ.": "ທາດແປ້ງສີຂາວມີດັດຊະນີນ້ຳຕານສູງ ແລະ ປ່ຽນເປັນນ້ຳຕານໃນເລືອດຢ່າງໄວວາ. ຈຳກັດ: ເຂົ້າຂາວ (ບໍ່ເກີນ 1 ຖ້ວຍ/ຄາບ), ເຂົ້າຈີ່ຂາວ, ເສັ້ນໝີ່, ເຂົ້າໜົມປັງ. ແທນທີ່ດ້ວຍທັນຍາພືດເຕັມເມັດແລະຜັກ.",
    "Rượu bia có thể gây hạ đường huyết nguy hiểm, đặc biệt khi bụng đói hoặc khi đang dùng thuốc tiểu đường. Nếu uống: không uống khi đói, uống cùng bữa ăn, giới hạn 1-2 đơn vị/ngày. Không uống nếu đường huyết đang thấp.": "ເຫຼົ້າສາມາດເຮັດໃຫ້ນ້ຳຕານໃນເລືອດຕ່ຳເປັນອັນຕະລາຍ, ໂດຍສະເພາະເມື່ອທ້ອງຫວ່າງ ຫຼື ເມື່ອກິນຢາປົວພະຍາດເບົາຫວານ. ຖ້າທ່ານດື່ມ: ຢ່າດື່ມເມື່ອທ້ອງຫວ່າງ, ດື່ມພ້ອມອາຫານ, ຈຳກັດ 1-2 ຫົວໜ່ວຍ/ມື້. ຢ່າດື່ມຖ້ານ້ຳຕານໃນເລືອດຕ່ຳ.",
    "Đi bộ nhẹ nhàng 15-30 phút sau bữa ăn giúp cơ thể sử dụng glucose hiệu quả hơn, từ đó hạ đường huyết sau ăn. Bắt đầu đi bộ khoảng 30-60 phút sau khi ăn xong. Tốc độ vừa phải, không cần nhanh.": "ການຍ່າງເບົາໆ 15-30 ນາທີຫຼັງອາຫານຊ່ວຍໃຫ້ຮ່າງກາຍນຳໃຊ້ກລູໂກສໄດ້ຢ່າງມີປະສິດທິພາບຫຼາຍຂຶ້ນ, ເຊິ່ງຊ່ວຍຫຼຸດນ້ຳຕານໃນເລືອດຫຼັງອາຫານ. ເລີ່ມຍ່າງປະມານ 30-60 ນາທີຫຼັງຈາກກິນອາຫານແລ້ວ. ຄວາມໄວປານກາງ, ບໍ່ຈຳເປັນຕ້ອງໄວ.",
    "Vận động thường xuyên giúp cơ thể nhạy cảm hơn với insulin, kiểm soát đường huyết tốt hơn và duy trì cân nặng khỏe mạnh. Khuyến nghị: ít nhất 150 phút vận động vừa/tuần. Các bài tập phù hợp: đi bộ, đạp xe, bơi lội, yoga, dưỡng sinh.": "ການອອກກຳລັງກາຍເປັນປະຈຳເຮັດໃຫ້ຮ່າງກາຍມີຄວາມອ່ອນໄຫວຕໍ່ອິນຊູລິນຫຼາຍຂຶ້ນ, ຄວບຄຸມນ້ຳຕານໃນເລືອດໄດ້ດີຂຶ້ນ, ແລະ ຮັກສານ້ຳໜັກໃຫ້ແຂງແຮງ. ຄຳແນະນຳ: ຢ່າງໜ້ອຍ 150 ນາທີຂອງການອອກກຳລັງກາຍປານກາງ/ອາທິດ. ການອອກກຳລັງກາຍທີ່ເໝາະສົມ: ຍ່າງ, ຂີ່ລົດຖີບ, ລອຍນ້ຳ, ໂຍຄະ.",
    "Triệu chứng hạ đường huyết: run tay, vã mồ hôi, tim đập nhanh, chóng mặt, yếu sức, đói cồn cào, mờ mắt, khó tập trung. Xử lý ngay: Ăn ngay 15g đường nhanh (3 viên đường hoặc 150ml nước trái cây hoặc 1 muỗng canh mật ong). Nghỉ ngơi 15 phút rồi đo lại đường huyết. Nếu vẫn thấp hoặc không tỉnh táo, gọi cấp cứu 115 ngay lập tức.": "ອາການຂອງນ້ຳຕານໃນເລືອດຕ່ຳ: ສັ່ນ, ເຫື່ອອອກ, ຫົວໃຈເຕັ້ນໄວ, ວິນຫົວ, ອ່ອນເພຍ, ຫິວຫຼາຍ, ຕາພາງ, ຍາກທີ່ຈະຕັ້ງໃຈ. ຈັດການທັນທີ: ກິນນ້ຳຕານທີ່ອອກລິດຕົວໄວ 15g (ນ້ຳຕານ 3 ກ້ອນ ຫຼື ນ້ຳໝາກໄມ້ 150ml ຫຼື ນ້ຳເຜິ້ງ 1 ບ່ວງ). ພັກຜ່ອນ 15 ນາທີແລ້ວກວດອີກຄັ້ງ. ຖ້າຍັງຕ່ຳ ຫຼື ໝົດສະຕິ, ໂທ 115 ທັນທີ.",
    "Triệu chứng tăng đường huyết nguy hiểm: khát nước dữ dội, tiểu nhiều, mờ mắt, đau đầu, mệt mỏi, buồn nôn. Nếu đường huyết > 13.9 mmol/L kèm triệu chứng trên, cần liên hệ bác sĩ ngay. Nếu > 16.7 mmol/L hoặc có nôn mửa, khó thở — gọi cấp cứu 115.": "ອາການຂອງນ້ຳຕານໃນເລືອດສູງອັນຕະລາຍ: ຫິວນ້ຳຫຼາຍ, ຍ່ຽວເລື້ອຍໆ, ຕາພາງ, ເຈັບຫົວ, ອ່ອນເພຍ, ປວດຮາກ. ຖ້ານ້ຳຕານໃນເລືອດ > 13.9 mmol/L ພ້ອມກັບອາການເຫຼົ່ານີ້, ຕິດຕໍ່ທ່ານໝໍທັນທີ. ຖ້າ > 16.7 mmol/L ຫຼື ມີອາການຮາກ, ຫາຍໃຈຍາກ — ໂທ 115."
  }
};

const langs = ['vi', 'en', 'lo'];

langs.forEach(lang => {
  const filePath = path.join(__dirname, `frontend/src/i18n/${lang}.js`);
  let content = fs.readFileSync(filePath, 'utf-8');
  
  Object.entries(data[lang]).forEach(([k, v]) => {
    // If we find `adviceData: {`, we just add these fields to it
    // But since it's hard to parse JS, we can just replace `adviceData: {` with `adviceData: { "KEY": "VAL",`
    const escapedK = k.replace(/"/g, '\\"');
    const escapedV = v.replace(/"/g, '\\"');
    content = content.replace('adviceData: {', `adviceData: {\n    "${escapedK}": "${escapedV}",`);
  });
  
  fs.writeFileSync(filePath, content);
  console.log(`Updated details for ${lang}.js`);
});
