import json
import re

# Khôi's Landing translations
kh_vi = {
    "navHome": "Trang chủ",
    "navFeatures": "Tính năng",
    "navImpact": "Tác động",
    "navContact": "Liên hệ",
    "heroBadge": "Trợ lý sức khỏe thông minh",
    "heroTitle1": "Quản lý tiểu đường",
    "heroTitle2": "Dễ dàng hơn bao giờ hết",
    "heroSubtitle": "DIA+ giúp bạn theo dõi đường huyết, nhắc nhở uống thuốc và phân tích đơn thuốc tự động bằng AI.",
    "heroBtn": "Bắt đầu miễn phí",
    "downloadIOS": "Tải trên App Store",
    "downloadAndroid": "Tải trên Google Play",
    "discoverBadge": "Tính năng nổi bật",
    "discoverTitle": "Công nghệ đột phá cho sức khỏe",
    "discoverSubtitle": "Được thiết kế tỉ mỉ để mang lại trải nghiệm chăm sóc y tế thông minh, thân thiện và hiệu quả nhất.",
    "f1Title": "Giọng nói người thân",
    "f1Desc": "Tính năng độc quyền giúp thu âm giọng nói của con cháu để nhắc nhở uống thuốc hoặc cảnh báo đường huyết.",
    "f1Demo": "\"Ông ơi, đến giờ uống thuốc rồi nhé!\"",
    "f1Effect": "Xóa nhòa khoảng cách thế hệ bằng giọng nói thân thương",
    "f2Title": "Quét đơn thuốc AI",
    "f2Desc": "Chỉ cần một bức ảnh, AI của DIA+ sẽ tự động phân tích tên thuốc, công dụng và liều dùng chính xác.",
    "f2Demo": "Đang phân tích dữ liệu...",
    "f2Effect": "Tiết kiệm 95% thời gian so với nhập tay thủ công",
    "f3Title": "Phân tích thông minh",
    "f3Desc": "Theo dõi đường huyết liên tục với biểu đồ trực quan. Hệ thống tự động cảnh báo 4 cấp độ giúp bạn can thiệp kịp thời.",
    "f3Demo": "Đường huyết ổn định",
    "f3Effect": "Cảnh báo nguy hiểm sớm hơn 30 phút",
    "f4Title": "Tự động lên lịch",
    "f4Desc": "Chỉ với một cú click, toàn bộ lịch uống thuốc và lịch khám bác sĩ sẽ được sắp xếp khoa học.",
    "f4Demo": "Đã lên lịch lúc 08:00 AM",
    "f4Effect": "Giảm 80% tỷ lệ quên uống thuốc",
    "f5Title": "Lưu bệnh án ngoại tuyến",
    "f5Desc": "Lưu trữ an toàn mọi lịch sử quét đơn thuốc. Ứng dụng hoạt động mượt mà ngay cả khi không có mạng.",
    "f5Demo": "Đã đồng bộ an toàn",
    "f5Effect": "Dữ liệu luôn sẵn sàng, kể cả ở vùng sâu vùng xa",
    "impactBadge": "Tác động thực tế",
    "impactTitle": "Con số nói lên tất cả",
    "impactSubtitle": "Chúng tôi không chỉ là một ứng dụng — chúng tôi là người bạn đồng hành mang lại giá trị thực tế cho hàng ngàn bệnh nhân.",
    "impact1Val": "1.2M+",
    "impact1Title": "Liều thuốc đúng giờ",
    "impact1Desc": "Hình thành thói quen tốt mỗi ngày",
    "impact2Val": "< 1s",
    "impact2Title": "Phân tích đơn thuốc",
    "impact2Desc": "Tốc độ xử lý bởi AI",
    "impact3Val": "95%",
    "impact3Title": "Đường huyết ổn định",
    "impact3Desc": "Sau 3 tháng sử dụng liên tục",
    "impact4Val": "24/7",
    "impact4Title": "Hệ thống giám sát",
    "impact4Desc": "Luôn bảo vệ sức khỏe bạn",
    "footerDesc": "DIA+ hỗ trợ người bệnh quản lý tiểu đường, theo dõi đường huyết và phân tích đơn thuốc tự động bằng AI.",
    "footerLinks": "Liên kết",
    "footerProjectRep": "ĐẠI DIỆN DỰ ÁN",
    "footerFounder": "Founder",
    "footerPhone": "SĐT",
    "footerPrivacy": "Chính sách bảo mật",
    "footerTerms": "Điều khoản",
    "footerCookies": "Cookie",
    "modalTitle": "Bạn muốn bắt đầu như thế nào?",
    "modalBtn1Title": "Đăng ký / Đăng nhập",
    "modalBtn1Desc": "Tôi muốn tạo tài khoản hoặc đăng nhập",
    "modalBtn2Title": "Trải nghiệm nhanh (Demo)",
    "modalBtn2TitleLoading: ": "Đang vào...",
    "modalBtn2Desc": "Khám phá các tính năng bằng tài khoản dùng thử"
}

kh_en = {
    "navHome": "Home",
    "navFeatures": "Features",
    "navImpact": "Impact",
    "navContact": "Contact",
    "heroBadge": "Smart Health Assistant",
    "heroTitle1": "Diabetes Management",
    "heroTitle2": "Easier than ever",
    "heroSubtitle": "DIA+ helps you monitor blood sugar, reminds you to take medication, and analyzes prescriptions automatically using AI.",
    "heroBtn": "Start for free",
    "downloadIOS": "Download on App Store",
    "downloadAndroid": "Get it on Google Play",
    "discoverBadge": "Key Features",
    "discoverTitle": "Breakthrough Health Technology",
    "discoverSubtitle": "Meticulously designed to provide the most intelligent, user-friendly, and effective healthcare experience.",
    "f1Title": "Family Voice Alerts",
    "f1Desc": "An exclusive feature that records the voices of grandchildren to remind you to take medication or warn about blood sugar.",
    "f1Demo": "\"Grandpa, it's time for your medicine!\"",
    "f1Effect": "Bridge the generation gap with familiar voices",
    "f2Title": "AI Prescription Scan",
    "f2Desc": "With just one photo, DIA+ AI automatically and accurately analyzes drug names, uses, and dosages.",
    "f2Demo": "Analyzing data...",
    "f2Effect": "Save 95% of time compared to manual entry",
    "f3Title": "Smart Analysis",
    "f3Desc": "Continuously monitor blood sugar with intuitive charts. The system automatically warns at 4 levels helping you intervene promptly.",
    "f3Demo": "Blood sugar is stable",
    "f3Effect": "Detect danger signals 30 minutes earlier",
    "f4Title": "Auto Scheduling",
    "f4Desc": "With just one click, your entire medication schedule and doctor appointments will be scientifically arranged.",
    "f4Demo": "Scheduled at 08:00 AM",
    "f4Effect": "Reduce missed doses by 80%",
    "f5Title": "Offline Medical Records",
    "f5Desc": "Safely store all your prescription scan history. The application works smoothly even when the phone has no internet connection.",
    "f5Demo": "Safely synchronized",
    "f5Effect": "Data always available, even in remote areas",
    "impactBadge": "Real Impact",
    "impactTitle": "Numbers speak for themselves",
    "impactSubtitle": "We are more than an app — we are a companion bringing real value to thousands of patients.",
    "impact1Val": "1.2M+",
    "impact1Title": "On-time Doses",
    "impact1Desc": "Building healthy habits every day",
    "impact2Val": "< 1s",
    "impact2Title": "AI Prescription Scan",
    "impact2Desc": "Lightning fast AI processing",
    "impact3Val": "95%",
    "impact3Title": "Stable Blood Sugar",
    "impact3Desc": "After 3 months of continuous use",
    "impact4Val": "24/7",
    "impact4Title": "Monitoring System",
    "impact4Desc": "Always protecting your health",
    "footerDesc": "DIA+ supports patients in managing diabetes, tracking blood sugar, and automatically analyzing prescriptions using AI.",
    "footerLinks": "Links",
    "footerProjectRep": "PROJECT REPRESENTATIVE",
    "footerFounder": "Founder",
    "footerPhone": "Phone",
    "footerPrivacy": "Privacy Policy",
    "footerTerms": "Terms",
    "footerCookies": "Cookies",
    "modalTitle": "How would you like to start?",
    "modalBtn1Title": "Register / Login",
    "modalBtn1Desc: ": "I want to create an account or login",
    "modalBtn2Title": "Quick Experience (Demo)",
    "modalBtn2TitleLoading": "Entering...",
    "modalBtn2Desc": "Explore features instantly with a trial account"
}

kh_lo = {
    "navHome": "ໜ້າຫຼັກ",
    "navFeatures": "ຄຸນສົມບັດ",
    "navImpact": "ຜົນກະທົບ",
    "navContact": "ຕິດຕໍ່",
    "heroBadge": "ຜູ້ຊ່ວຍສຸຂະພາບອັດສະລິຍະ",
    "heroTitle1": "ການຈັດການເບົາຫວານ",
    "heroTitle2": "ງ່າຍກວ່າທີ່ເຄີຍ",
    "heroSubtitle": "DIA+ ຊ່ວຍທ່ານຕິດຕາມນ້ຳຕານໃນເລືອດ, ເຕືອນໃຫ້ກິນຢາ, ແລະ ວິເຄາະໃບສັ່ງຢາອັດຕະໂນມັດດ້ວຍ AI.",
    "heroBtn": "ເລີ່ມຕົ້ນຟຣີ",
    "downloadIOS": "ດາວໂຫຼດໃນ App Store",
    "downloadAndroid": "ດາວໂຫຼດໃນ Google Play",
    "discoverBadge": "ຄຸນສົມບັດຫຼັກ",
    "discoverTitle": "ເຕັກໂນໂລຊີສຸຂະພາບລ້ຳສະໄໝ",
    "discoverSubtitle": "ອອກແບບມາເພື່ອໃຫ້ປະສົບການການດູແລສຸຂະພາບທີ່ສະຫຼາດ, ເປັນມິດ, ແລະ ມີປະສິດທິພາບທີ່ສຸດ.",
    "f1Title": "ສຽງເຕືອນຈາກຄອບຄົວ",
    "f1Desc": "ຄຸນສົມບັດພິເສດທີ່ບັນທຶກສຽງຂອງລູກຫຼານເພື່ອເຕືອນໃຫ້ກິນຢາ ຫຼື ເຕືອນນ້ຳຕານໃນເລືອດ.",
    "f1Demo": "\"ພໍ່ຕູ້, ຮອດເວລາກິນຢາແລ້ວເດີ້!\"",
    "f1Effect": "ຫຼຸດຜ່ອນຊ່ອງຫວ່າງລະຫວ່າງໄວດ້ວຍສຽງທີ່ຄຸ້ນເຄີຍ",
    "f2Title": "ສະແກນໃບສັ່ງຢາດ້ວຍ AI",
    "f2Desc": "ພຽງແຕ່ຮູບດຽວ, AI ຂອງ DIA+ ຈະວິເຄາະຊື່ຢາ, ວິທີໃຊ້, ແລະ ປະລິມານອັດຕະໂນມັດ.",
    "f2Demo": "ກຳລັງວິເຄາະຂໍ້ມູນ...",
    "f2Effect": "ປະຢັດເວລາ 95% ທຽບກັບການພິມດ້ວຍມື",
    "f3Title": "ການວິເຄາະອັດສະລິຍະ",
    "f3Desc": "ຕິດຕາມນ້ຳຕານໃນເລືອດດ້ວຍກຣາຟທີ່ຊັດເຈນ. ລະບົບເຕືອນອັດຕະໂນມັດ 4 ລະດັບ.",
    "f3Demo": "ນ້ຳຕານໃນເລືອດປົກກະຕິ",
    "f3Effect": "ເຕືອນສັນຍານອັນຕະລາຍກ່ອນ 30 ນາທີ",
    "f4Title": "ຈັດຕາຕະລາງອັດຕະໂນມັດ",
    "f4Desc": "ພຽງຄລິກດຽວ, ຕາຕະລາງກິນຢາ ແລະ ນັດໝາຍແພດຈະຖືກຈັດແຈງຢ່າງເປັນລະບຽບ.",
    "f4Demo": "ຈັດຕາຕະລາງສຳເລັດເວລາ 08:00 AM",
    "f4Effect": "ຫຼຸດອັດຕາການລືມກິນຢາລົງ 80%",
    "f5Title": "ບັນທຶກສຸຂະພາບອອບລາຍ",
    "f5Desc": "ບັນທຶກປະຫວັດການສະແກນຢາຢ່າງປອດໄພ. ແອັບເຮັດວຽກໄດ້ເຖິງແມ່ນວ່າບໍ່ມີອິນເຕີເນັດ.",
    "f5Demo": "ຊິ້ງຂໍ້ມູນຢ່າງປອດໄພແລ້ວ",
    "f5Effect": "ຂໍ້ມູນພ້ອມໃຊ້ງານສະເໝີ, ເຖິງຢູ່ເຂດຫ່າງໄກ",
    "impactBadge": "ຜົນກະທົບຕົວຈິງ",
    "impactTitle": "ຕົວເລກບອກທຸກຢ່າງ",
    "impactSubtitle": "ພວກເຮົາບໍ່ແມ່ນພຽງແຕ່ແອັບ — ພວກເຮົາຄືເພື່ອນຮ່ວມທາງທີ່ນຳເອົາຄຸນຄ່າແທ້ຈິງໃຫ້ກັບຄົນເຈັບ.",
    "impact1Val": "1.2M+",
    "impact1Title": "ກິນຢາຕົງເວລາ",
    "impact1Desc": "ສ້າງນິໄສທີ່ດີທຸກໆມື້",
    "impact2Val": "< 1s",
    "impact2Title": "ສະແກນໃບສັ່ງຢາ",
    "impact2Desc": "ຄວາມໄວການປະມວນຜົນດ້ວຍ AI",
    "impact3Val": "95%",
    "impact3Title": "ນ້ຳຕານໃນເລືອດຄົງທີ່",
    "impact3Desc": "ຫຼັງຈາກນຳໃຊ້ຕໍ່ເນື່ອງ 3 ເດືອນ",
    "impact4Val": "24/7",
    "impact4Title": "ລະບົບຕິດຕາມ",
    "impact4Desc": "ປົກປ້ອງສຸຂະພາບຂອງທ່ານສະເໝີ",
    "footerDesc": "DIA+ ຊ່ວຍຜູ້ป่วยໃນການຈັດການເບົາຫວານ, ຕິດຕາມນ້ຳຕານໃນເລືອດ ແລະ ວິເຄາະໃບສັ່ງຢາດ້ວຍ AI.",
    "footerLinks": "ລິ້ງຄ໌",
    "footerProjectRep": "ຕົວແທນໂຄງການ",
    "footerFounder": "ຜູ້ກໍ່ຕັ້ງ",
    "footerPhone": "ເບີໂທ",
    "footerPrivacy": "ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ",
    "footerTerms": "ເງື່ອນໄຂ",
    "footerCookies": "ຄຸກກີ້",
    "modalTitle": "ທ່ານຕ້ອງການເລີ່ມຕົ້ນແນວໃດ?",
    "modalBtn1Title": "ລົງທະບຽນ / ເຂົ້າສູ່ລະບົບ",
    "modalBtn1Desc": "ຂ້ອຍຕ້ອງການສ້າງບັນຊີ ຫຼື ເຂົ້າສູ່ລະບົບ",
    "modalBtn2Title": "ທົດລອງໃຊ້ດ່ວນ (Demo)",
    "modalBtn2TitleLoading": "ກຳລັງເຂົ້າ...",
    "modalBtn2Desc": "ສຳຫຼວດຄຸນສົມບັດທັນທີດ້ວຍບັນຊີທົດລອງ"
}

def dict_to_js(d, indent=4):
    lines = ["{\n"]
    for k, v in d.items():
        v = v.replace("\"", "\\\"").replace("\n", "\\n")
        lines.append(f"{' ' * indent}{k}: '{v}',\n")
    lines.append(f"{' ' * (indent-2)}}}")
    return "".join(lines)

def replace_landing_in_file(filepath, obj):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Replace the landing object
    # It assumes the landing block is formatted similarly in all files
    pattern = re.compile(r"  landing:\s*\{.*?\}(?=,[\s\n]+//|,\n  nav)", re.DOTALL)
    
    js_obj = dict_to_js(obj, indent=4)
    new_content = pattern.sub(f"  landing: {js_obj}", content)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)

replace_landing_in_file('/Users/quynghienroi/Documents/GitHub/IPUNI-NEW-/frontend/src/i18n/vi.js', kh_vi)
replace_landing_in_file('/Users/quynghienroi/Documents/GitHub/IPUNI-NEW-/frontend/src/i18n/en.js', kh_en)
replace_landing_in_file('/Users/quynghienroi/Documents/GitHub/IPUNI-NEW-/frontend/src/i18n/lo.js', kh_lo)
print("Updated i18n files")
